### ISSUE TITLE
Bug: truffle-plugin-verify listed as a plugin, but not found in global or local node modules!

### ISSUE THREAD

**Issue by arsandov** [rkalis/truffle-plugin-verify#153]
**Describe the bug**

I tried to run `truffle run verify MetaCoin --network rinkeby` in a newly deployed contract and got the error Bug: truffle-plugin-verify listed as a plugin, but not found in global or local node modules! 

**Steps To Reproduce**

1. Install Truffle
2. Write a contract and deploy it
3. Install the plugin
4. Try to verify a contract

**Environment information**

Please provide environment information as complete as possible. Before submitting a bug report, please make sure that you're running an LTS version of Node and the latest versions of Truffle and truffle-plugin-verify.

- Operating System: Ubuntu 18.04.6 LTS (Bionic Beaver)
- Node version: v16.14.0
- Truffle version: v5.5.0
- truffle-plugin-verify version: v0.5.21

**Debug output**

```
Error: truffle-plugin-verify listed as a plugin, but not found in global or local node modules!

    at new ExtendableError (/home/user/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/plugins/node_modules/@truffle/error/index.js:10:1)
    at Object.normalizeConfigPlugins (/home/user/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/plugins/dist/lib/utils.js:30:1)
    at Function.checkPluginModules (/home/user/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/plugins/dist/lib/Plugins.js:50:1)
    at Function.listAll (/home/user/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/plugins/dist/lib/Plugins.js:17:1)
    at Function.findPluginsForCommand (/home/user/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/plugins/dist/lib/Plugins.js:25:1)
    at Object.run (/home/user/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/run/runHandler.js:7:1)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at bound run (node:internal/util:346:12)
    at Object.module.exports [as run] (/home/user/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/run/run.js:18:1)
    at Command.run (/home/user/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1)
Truffle v5.5.0 (core: 5.5.0)
Node v16.14.0
```

**Comment by arsandov** [comment]
It turns out that the problem might be a compatibility issue with the latest version of Truffle, I was able to solve it using:
`npm install truffle@5.1.14-nodeLTS.0`. Hopefully, this saves someone else time. Feel free to close it.

**Comment by rkalis** [comment]
Afaik the plugin works with newer versions of Truffle. I've used the plugin last weekend with Truffle v5.5.4 (pretty recent version). If you have reason to believe it doesn't work with recent versions of Truffle, please open an issue with clear steps to reproduce.
