### ISSUE TITLE
Fail with TypeError: (intermediate value).hostname.split(...).at at Goerli

### ISSUE THREAD

**Issue by m-lukyanov** [rkalis/truffle-plugin-verify#190]
Today it stopped  to verify after installing the latest version.

I'm trying npx truffle run verify <contratc_name> --network goerli

Such issue was solved recently but for polygon. #189 

Operation system: Windows 10

**Debug output**

```
Running truffle-plugin-verify v0.5.33
Retrieving network's network ID & chain ID
TypeError: (intermediate value).hostname.split(...).at is not a function
    at getApiKey (E:\sources\erc721a\node_modules\erc721a\node_modules\truffle-plugin-verify\dist\util.js:141:58)
    at E:\sources\erc721a\node_modules\erc721a\node_modules\truffle-plugin-verify\dist\verify.js:92:41
    at Generator.next (<anonymous>)
    at fulfilled (E:\sources\erc721a\node_modules\erc721a\node_modules\truffle-plugin-verify\dist\verify.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Truffle v5.5.30 (core: 5.5.30)
Node v14.18.1
```

**Comment by m-lukyanov** [comment]
npm install -D truffle-plugin-verify@0.6.1 solved the problem )
