### ISSUE TITLE
Ipfs connect fail when verify contracts

### ISSUE THREAD

**Issue by doublepupilla** [rkalis/truffle-plugin-verify#32]
Query:
 `truffle plugin run verify contract-name --network ropsten [--debug]`

Output:
```
> Warning: possible unsupported (undocumented in help) command line option: --network
Finding publishable artifacts...
Uploading sources and publishing to registry...
Error: [ipfs-mini] status 0: Error: connect ETIMEDOUT 67.228.102.32:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
    at exports.XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/ipfs-mini/src/index.js:63:1)
    at exports.XMLHttpRequest.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:1)
    at setState (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:1)
    at exports.XMLHttpRequest.handleError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:532:1)
    at ClientRequest.errorHandler (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:1)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Truffle v5.1.5 (core: 5.1.5)
Node v10.18.0

```
In order to identify whether my local network problem，i test the ip by `http://port.ping.pe`,  unfortunately all of them connect fail
```
31.13.72.34:5001        
66.220.151.20:5001       
67.228.74.123:5001  
67.228.102.32:5001     
67.228.235.93:5001       
67.228.235.91:5001       
69.171.227.37:5001       
75.126.115.192:5001      
208.43.237.140:5001      
199.59.150.49:5001 
```

**Comment by doublepupilla** [comment]
Thanks your reply.
my original project workspace runs `truffle plugin run verify` instead of `truffle run verify` because of the root node_modules of the workspace problem.  the result is the mentioned above. It seems that the two commands are different, the verify.js didn't execute actually.  

I reopen a separate truffle project to test by `truffle run verify` command, it works but the timeout issue is still exits.

Query:
`truffle run verify ContractName@ContractAddr --network ropsten --debug`
Output:
```
DEBUG logging is turned ON
Running truffle-plugin-verify v0.3.11
Verifying ContractName@ContractAddr
Reading artifact file at /Users/dbpupilla/projects/truffle-cr/build/contracts/ContractName.json
Custom address ContractAddr specified
Retrieving constructor parameters from https://api-ropsten.etherscan.io/api?apiKey=MyApiKey&module=account&action=txlist&address=ContractAddr&page=1&sort=asc&offset=1
connect ETIMEDOUT 75.126.215.88:443
Failed to connect to Etherscan API at url https://api-ropsten.etherscan.io/api
Failed to verify 1 contract(s): ContractName@ContractAddr
```
`connect ETIMEDOUT 75.126.215.88:443` is the log that i add to source to catch error.   The problem is the timeout of the request by axios
```
    logger.debug(`Retrieving constructor parameters from ${url}`)
    res = await axios.get(url)
```
It's strange that  the res works fine by open the url on browser, but the error triggered by timeout. the request ip also connect fail by the ping test.

**Comment by rkalis** [comment]
That is very odd indeed. Perhaps there is something in your computer's settings that is prohibiting you to connect to the internet from the terminal? Are you able to connect to other websites through the terminal (e.g. `curl https://www.google.com`)?

**Comment by rkalis** [comment]
Or a different possibility, there might be something wrong in the DNS resolution in the terminal, since I don't recognise `75.126.215.88` as the correct IP for Etherscan. If I do `dig api-ropsten.etherscan.io`, I get the following IP addresses:

```
api-ropsten.etherscan.io. 300	IN	A	172.67.8.107
api-ropsten.etherscan.io. 300	IN	A	104.22.15.57
api-ropsten.etherscan.io. 300	IN	A	104.22.14.57
```

**Comment by doublepupilla** [comment]
yes, it's network blocking. the problem has been fixed. thanks for your help

**Comment by rkalis** [comment]
Good to hear!
